const RouteName = {
  SPLASH_SCREEN: 'SplashScreen',
  GET_STARTED_SCREEN: 'GetstartedSliderscreen',
  LOGIN_AND_REGISTRATION: 'LoginandRegistrationScreen',
  WELCOME_SUMANYA: 'WelcomeSumnya',
  LOCATION_HOME_OFFICE_SCREEN: 'LocationHomeOfficeScreen',
  CONFORMLOCATION_SET: 'ConformLocation',
  HOME_SCREEN: 'Homescreen',
  CUSTOMERS: 'Customers',
  HOSPITAL_MEDICINE_SCREEN: 'items',
  PRODUCT_LIST_ITEM: 'ProductItemList',
  PRODUCT_DETAILS_SCREEN: 'ProductDetailesScreen',
  OFFERS_TAB: 'OffersTab',
  CART_TAB: 'Sale Returns',
  CHECK_OUT: 'CheckOutScreen',
  ACCOUNT_TAB_SET: 'Profile',
  HOME_TAB: 'Home',
  DRAWER_HELP_SCREEN: 'DrawerHelpScreen',
  PAYMENTSCREEN: 'PaymentScreen',
  SETTTING_SCREEN: 'SettingsScreen',
  ALL_BOOK_MARK_SCREEN: 'AllBookMarkScreen',
  NOTIFICATION_SCREEN: 'DrawerNavigationNotification',
  YOUR_ORDER_SCREEN: 'Invoices',
  SUMMARY_INVOICE: 'SummaryInvoice',
  YOUR_CHAT: 'DrawerChatScreen',
  OTP_VERIFY_SCREEN: 'OtpVeryfyScreen',
  ORDER_TAB_SCREEN: 'AddOrderitemScreen',
  CHEQUE_DETAILS: 'ChequeDetails',
  PAYMENT_SUCCESSFULLY: 'PaytmSuccessFully',
  RATING_SCREEN_SET: 'RatingScreen',
  EDIT_LOCATION_SCREEN: 'EditLocationScreen',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  ADD_ORDER_ITEM: 'AddOrderitemScreen',
  FORGET_PASSWORD_SCREEN: 'ForgotPassword',
};
export default RouteName;
