const RouteName = {
  SPLASH_SCREEN: 'SplashScreen',
  GET_STARTED_SCREEN: 'GetstartedSliderscreen',
  LOGIN_AND_REGISTRATION: 'LoginandRegistrationScreen',
  WELCOME_SUMANYA: 'WelcomeSumnya',
  LOCATION_HOME_OFFICE_SCREEN: 'LocationHomeOfficeScreen',
  CONFORMLOCATION_SET: 'ConformLocation',
  HOME_SCREEN: 'Homescreen',
  // POPULAR_SCREEN : "PopularCuisines",
  POPULAR_SCREEN: 'Customers',
  // FRIECE_RICE_LISTING_SCREEN : "HospitalsSMedicinecreen",
  HOSPITAL_MEDICINE_SCREEN: 'Medicine',
  PRODUCT_LIST_ITEM: 'ProductItemList',
  // SELECT_ITEM_SCREEN_15 : "SelectItem_15",
  PRODUCT_DETAILS_SCREEN: 'ProductDetailesScreen',
  OFFERS_TAB: 'OffersTab',
  CART_TAB: 'Sale Returns',
  CHECK_OUT: 'CheckOutScreen',
  ACCOUNT_TAB_SET: 'Profile',
  HOME_TAB: 'Home',
  // HELP_SCREEN_SET : "Listing_page_22",
  DRAWER_HELP_SCREEN: 'DrawerHelpScreen',
  // MENEGE_PAYMENT_METHODE_24 : "MangePayment_24",
  PAYMENTSCREEN: 'PaymentScreen',
  SETTTING_SCREEN: 'SettingsScreen',
  ALL_BOOK_MARK_SCREEN: 'AllBookMarkScreen',
  NOTIFICATION_SCREEN: 'DrawerNavigationNotification',
  YOUR_ORDER_SCREEN: 'Invoices',
  YOUR_CHAT: 'DrawerChatScreen',
  OTP_VERIFY_SCREEN: 'OtpVeryfyScreen',
  // FASTFOOD_BOAT_SCREEN : "FastFoodBoat",
  // YOURORDER_SCREEN_36 : "AddOrderitemScreen",
  ORDER_TAB_SCREEN: 'AddOrderitemScreen',
  CREDIT_CARD_SCREEN_SET: 'CreditCardScreen',
  PAYMENT_SUCCESSFULLY: 'PaytmSuccessFully',
  RATING_SCREEN_SET: 'RatingScreen',
  EDIT_LOCATION_SCREEN: 'EditLocationScreen',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  // CHAT_SCREEN_SET : "DrawerChatScreen",
  ADD_ORDER_ITEM: 'AddOrderitemScreen',
  FORGET_PASSWORD_SCREEN: 'ForgotPassword',
};
export default RouteName;