import { SF,SW,wp,hp,colors, Fonts, ColorTheme} from '../../utils';
import { StyleSheet, Dimensions } from 'react-native';
const { height: SCREEN_HEIGHT } = Dimensions.get("window");

const IS_IPHONE_X = SCREEN_HEIGHT === 812 || SCREEN_HEIGHT === 896;
const STATUS_BAR_HEIGHT = 0;
const HEADER_HEIGHT = 64;
const NAV_BAR_HEIGHT = HEADER_HEIGHT - STATUS_BAR_HEIGHT;

export default StyleSheet.create({
  minstyleviewphotograpgy: {
    flexDirection: 'row',
    justifyContent: 'center',
    // alignItems: 'center',
    height: '100%',
    width: '100%',
    // backgroundColor:'hsl(0, 0%, 94.9%)',
    backgroundColor: 'white',
  },
  bgcolorset: {
    backgroundColor: ColorTheme.BGScreen,
  },
  minviewsigninscreen: {
    width: '100%',
    paddingHorizontal: '5%',
  },

  minflexview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  useraccountwhitebox: {
    width: '100%',
    marginTop: 20,
    borderRadius: 20,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 30,
    backgroundColor: ColorTheme.LighColorFour,
    shadowColor: 'rgba(0, 0, 0, 0.06)',
    shadowOffset: {
      width: 345,
      height: Platform.OS === 'ios' ? 2 : 25,
    },
    shadowOpacity: 0.58,
    shadowRadius: Platform.OS === 'ios' ? 2 : 25,
    elevation: Platform.OS === 'ios' ? 1 : 0,
  },
  flexrowtwxtspace: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: '2%',
    paddingTop: 10,
  },
  persnaltext: {
    fontSize: 17,
    fontWeight: '700',
    color: '#000000',
    fontFamily: Fonts.Metropolis_Medium,
  },
  edittextset: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
  },
  imagesetus: {
    height: 90,
    width: 90,
    borderRadius: 45,
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  fleximageandtext: {
    flexDirection: 'row',
  },
  sumanyatextset: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
    fontFamily: Fonts.Metropolis_Medium,
    marginBottom: 4,
  },
  setgimailtext: {
    fontSize: 13,
    fontWeight: '500',
    color: '#666',
    fontFamily: Fonts.Metropolis_Medium,
    flex: 1,
  },
  setgimailtextwo: {
    fontSize: 13,
    fontWeight: '500',
    color: '#666',
    fontFamily: Fonts.Metropolis_Medium,
    flex: 1,
  },
  addreshtext: {
    fontSize: 13,
    fontWeight: '500',
    color: '#666',
    fontFamily: Fonts.Metropolis_Medium,
    flex: 1,
  },
  setviewwidth: {
    width: '53%',
  },
  setbgcolorwhite: {
    backgroundColor: 'hsl(0, 0%, 94.9%)',
    width: '22%',
    marginRight: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 13,
  },
  flexrowsettile: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  bookmarktextstyle: {
    fontSize: 9,
    paddingTop: 4,
    fontWeight: '600',
    color: 'black',
    fontFamily: Fonts.Metropolis_Medium,
  },
  flexrowsetbgcolor: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 15,
    marginBottom: 20,
  },
  setbgcolordata: {
    backgroundColor: ColorTheme.LighColorFour,
    borderRadius: 20,
    height: 50,
    paddingHorizontal: '5%',
    justifyContent: 'space-between',
    paddingRight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  flexrowset: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: '5%',
    paddingRight: 40,
  },
  usertextstyle: {
    fontSize: 18,
    fontFamily: Fonts.Poppins_Medium,
    fontWeight: '700',
    marginRight: 10,
  },
  fourtextminview: {
    marginTop: 30,
    marginBottom: 30,
  },
  sendfeedbacktext: {
    fontSize: 18,
    color: '#000000',
    fontFamily: Fonts.Metropolis_Medium,
    fontWeight: '600',
    paddingBottom: 13,
  },
  setbgwhiteabout: {
    backgroundColor: ColorTheme.LighColorFour,
    width: '35%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 9,
    marginBottom: 30,
    borderRadius: 100,
  },
  abouttextstyle: {
    fontSize: 17,
    color: '#000000',
    fontFamily: Fonts.Metropolis_Medium,
    fontWeight: '600',
    marginLeft: 10,
  },
  updatebutton: {
    borderRadius: 100,
  },
  textstyleupdate: {
    color: 'white',
  },
  setbuttonstyleview: {
    marginTop: 20,
    marginBottom: 40,
  },
  profileImageContainer: {
    position: 'relative',
    marginRight: 15,
  },
  editIconBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  quickActionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  quickActionCard: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    fontFamily: Fonts.Metropolis_Medium,
  },
  menuItemContainer: {
    marginTop: 12,
  },
  menuItem: {
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  menuItemText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    fontFamily: Fonts.Metropolis_Medium,
    flex: 1,
  },
  chevronIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginBottom: 16,
    fontFamily: Fonts.Metropolis_Medium,
  },
  footerSection: {
    marginTop: 24,
    marginBottom: 30,
  },
  footerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  footerIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  footerButtonText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    fontFamily: Fonts.Metropolis_Medium,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginLeft: 10,
    fontFamily: Fonts.Metropolis_Medium,
  },
});
