const images = {
  splashscreenlogo_set_image: require('./Splaces.jpg'),
  // splashscreenlogo_set_image: require('./Splaces2.jpg'),
  // medicine_image: require('./applogo.png'),
  medicine_image: require('./medicine.png'),
  // Slider_one_img: require('./doctertablettwo.png'),
  Slider_two_img: require('./medicine.png'),
  Slider_three_img: require('./medicine.png'),
  facebookimage_set: require('./medicine.png'),
  Googleimg_set: require('./medicine.png'),
  Facebbok_bg_img_Set: require('./medicine.png'), 
  // Baby_care_imag: require('./babycareimage.png'),
  // Baby_care_imag_two: require('./Healthimag.png'),
  // Baby_care_imag_three: require('./womencareimg.png'),
  // Baby_care_imag_four: require('./personalcare.png'),
  // Baby_care_imag_five: require('./ayurvedimag.png'),
  Baby_care_imag_six: require('./medicine.png'),
  // Baby_care_imag_saven: require('./Homeesentials.png'),
  // Baby_care_imag_aeight: require('./appololife.png'),
  // Baby_care_imag_nine: require('./helthconditions.png'),
  Baby_care_imag_ten: require('./medicine.png'),
  // Docter_tablet_imag: require('./doctertablet.png'),
  Docter_tablet_imag_two: require('./medicine.png'),
  // Docter_tablet_imag_three: require('./doctertanlet3.png'),
  // Docter_tablet_imag_four: require('./docterimage5.png'),
  // Docter_tablet_imag_five: require('./docterimage8.png'),
  // Docter_tablet_imag_six: require('./docterimag10.png'),
  // Docter_tablet_imag_saven: require('./doctertabletsacven.png'),
  Docter_tablet_imag_aeight: require('./medicine.png'),
  Docter_background_remove_tablet : require('./medicine.png'),
  Docter_background_remove_tablet_two : require('./medicine.png'),
  Docter_background_remove_tablet_three : require('./medicine.png'),
  Docter_background_remove_tablet_four : require('./medicine.png'),
  Docter_background_remove_tablet_five : require('./medicine.png'),
  Docter_background_remove_tablet_six : require('./medicine.png'),
  Docter_background_remove_tablet_saven : require('./medicine.png'),
  Docter_background_remove_tablet_aeight : require('./medicine.png'),
  discount_img_parsanteg: require('./medicine.png'),
  // all_hospital_saven_img: require('./hospitalimgone.png'),
  all_hospital_saven_img_two: require('./medicine.png'),
  all_hospital_saven_img_three: require('./medicine.png'),
  all_hospital_saven_img_four: require('./medicine.png'),
  // all_hospital_saven_img_five: require('./hopitalsiximg.png'),
  all_hospital_saven_img_six: require('./medicine.png'),
  all_hospital_saven_img_saven: require('./medicine.png'),
  short_pharmacvy_imges: require('./medicine.png'),
  Account_image_user: require('./medicine.png'),
  Payimag: require('./medicine.png'),
  Sodexo_image_set: require('./medicine.png'),
  Paypal_image: require('./medicine.png'),
  // Paytem_image: require('./paytem.png'),
  google_pay_image: require('./medicine.png'),
  // Phone_Pay_Image: require('./phonepay.png'),
  Upiwidth_image: require('./medicine.png'),
  Mobik_image_logo: require('./medicine.png'),
  Freecharge_logo_png: require('./medicine.png'),
  // docter_slider_1_image: require('./selectfoode.png'),
  docter_slider_2_image: require('./medicine.png'),
  // docter_slider_3_image: require('./docter1.png'),
  // docter_slider_4_image: require('./docter4.png'),
  Crideit_card: require('./medicine.png'),
  Hdfcbanklogoimage_set: require('./medicine.png'),
  Repeat_Payment_image: require('./medicine.png'),
  Payment_succeful_one_image: require('./medicine.png'),
  // kotakbanklogi_image_one: require('./rupayimage.png'),
  // kotakbanklogi_image_two: require('./kotackimage.png'),
  kotakbanklogi_image_three: require('./medicine.png'),
  Search_image: require('./medicine.png'),
  Location_image: require('./medicine.png'),
  Successfully_image_set_rating: require('./medicine.png'),
  Successfully_color_picker_image: require('./medicine.png'),
  // Chat_image: require('./doctoreimageset.png'),
  // Bottel_imag: require('./bottelimage.png'),
  // Bottel_imag_two: require('./bottelimagtwo.png'),

  MedicalDealIMGOne: require('./medicine.png'),
  MedicalDealIMGTwo: require('./medicine.png'),
  MedicalDealIMGThree: require('./medicine.png'),
  MedicalDealIMGFour: require('./medicine.png'),
  MedicalDealIMGFive: require('./medicine.png'),
  MedicalDealIMGSix: require('./medicine.png'),
  MedicalDealIMGSeven: require('./medicine.png'),
  MedicalDealIMGEight: require('./medicine.png'), 
  MedicaleIMGOne: require('./medicine.png'),
  IngrediantsOne: require('./medicine.png'),
  IngrediantsTwo: require('./medicine.png'),
  IngrediantsThree: require('./medicine.png'),
  IngrediantsFour: require('./medicine.png'),
  IngrediantsFive: require('./medicine.png'),
  IngrediantsSix: require('./medicine.png'),
  IngrediantsSeven: require('./medicine.png'),
  IngrediantsEight: require('./medicine.png'),



}
export default images;